services:
  - type: web
    name: dha-digital-services
    env: node
    region: oregon
    plan: free
    buildCommand: |
      export NODE_OPTIONS="--max-old-space-size=4096"
      chmod +x render-build-production.sh
      bash render-build-production.sh
    startCommand: |
      chmod +x render-start-production.sh
      bash render-start-production.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20.19.0"
      - key: PORT
        generateValue: true
      - key: HOST
        value: 0.0.0.0
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health
    healthCheckTimeout: 300
    autoDeploy: true
    buildFilter:
      paths:
        - server/**
        - client/**
        - shared/**
        - package.json
        - render*.sh
    staticPublishPath: ./dist/public

  - type: worker
    name: dha-monitoring-service
    runtime: node
    plan: starter
    buildCommand: >
      bash -c "npm ci --prefer-offline --no-audit --legacy-peer-deps &&
      npm run build:monitor"
    startCommand: node dist/monitor.js
    buildFilter:
      paths: ["src/**", "monitor/**", "package.json", "package-lock.json"]
    envVars:
      - key: NODE_ENV
        value: production
      - key: ENABLE_MONITORING
        value: true
      - key: MONITOR_INTERVAL
        value: 60000
      - key: TARGET_SERVICE
        value: dha-digital-services
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: dha-digital-services
          envVarKey: RENDER_EXTERNAL_URL
      - key: DATABASE_URL
        fromService:
          type: web
          name: dha-digital-services
          envVarKey: DATABASE_URL
      - key: ALERT_WEBHOOK_URL
        sync: false
    autoscaling:
      min: 1
      max: 1