name: Deploy to Render
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json"
      
      - name: Wait for deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Waiting for deployment to complete..."
          while true; do
            STATUS=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" \
                    "https://api.render.com/v1/services/$RENDER_SERVICE_ID" \
                    | jq -r '.state')
            
            echo "Current status: $STATUS"
            
            if [ "$STATUS" = "live" ]; then
              echo "✅ Deployment successful!"
              break
            elif [ "$STATUS" = "failed" ]; then
              echo "❌ Deployment failed"
              exit 1
            fi
            
            sleep 30
          done